name: pylint
on: [pull_request]
jobs:
  steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "python_alelo tests"
        use-pylint: true
        use-pycodestyle: false
        use-flake8: false
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: "localization.py"
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""